<?php

add_action('init','of_options');

if (!function_exists('of_options')) {
function of_options(){

//Theme Shortname
$shortname = "reverb";


//Populate the options array
global $tt_options;
$tt_options = get_option('of_options');


//Access the WordPress Pages via an Array
$tt_pages = array();
$tt_pages_obj = get_pages('sort_column=post_parent,menu_order');    
foreach ($tt_pages_obj as $tt_page) {
$tt_pages[$tt_page->ID] = $tt_page->post_name; }
$tt_pages_tmp = array_unshift($tt_pages, "Select a page:"); 


//Access the WordPress Categories via an Array
$tt_categories = array();  
$tt_categories_obj = get_categories('hide_empty=0');
foreach ($tt_categories_obj as $tt_cat) {
$tt_categories[$tt_cat->cat_ID] = $tt_cat->cat_name;}
$categories_tmp = array_unshift($tt_categories, "Select a category:");


//Sample Array for demo purposes
$sample_array = array("1","2","3","4","5");


//Sample Advanced Array - The actual value differs from what the user sees
$font_array = array(
  "Abel" => "Abel",
		"Abril Fatface" => "Abril Fatface",
		"Aclonica" => "Aclonica",
		"Acme" => "Acme",
		"Actor" => "Actor ",
		"Adamina" => "Adamina",
		"Advent Pro" => "Advent Pro",
		"Aguafina Script" => "Aguafina Script",
		"Aladin" => "Aladin",
		"Aldrich" => "Aldrich ",
		"Alex Brush" => "Alex Brush",
		"Alfa Slab One" => "Alfa Slab One",
		"Alice" => "Alice ",
		"Alike Angular" => "Alike Angular",
		"Alike" => "Alike ",
		"Allan" => "Allan",
		"Allerta Stencil" => "Allerta Stencil",
		"Allerta" => "Allerta",
		"Allura" => "Allura",
		"Almendra SC" => "Almendra SC",
		"Almendra" => "Almendra",
		"Amaranth" => "Amaranth",
		"Amarante" => "Amarante",
		"Amatic SC" => "Amatic SC",
		"Amethysta" => "Amethysta",
		"Andada" => "Andada",
		"Andika" => "Andika ",
		"Annie Use Your Telescope" => "Annie Use Your Telescope",
		"Anonymous Pro" => "Anonymous Pro",
		"Antic Didone" => "Antic Didone",
		"Antic Slab" => "Antic Slab",
		"Antic" => "Antic",
		"Anton" => "Anton",
		"Arapey" => "Arapey",
		"Arbutus" => "Arbutus",
		"Architects Daughter" => "Architects Daughter",
		"Arimo" => "Arimo",
		"Arizonia" => "Arizonia",
		"Armata" => "Armata",
		"Artifika" => "Artifika",
		"Arvo" => "Arvo",
		"Asap" => "Asap",
		"Asset" => "Asset",
		"Astloch" => "Astloch",
		"Asul" => "Asul",
		"Atomic Age" => "Atomic Age",
		"Aubrey" => "Aubrey ",
		"Audiowide" => "Audiowide",
		"Average" => "Average",
		"Averia Gruesa Libre" => "Averia Gruesa Libre",
		"Averia Libre" => "Averia Libre",
		"Averia Sans Libre" => "Averia Sans Libre",
		"Averia Serif Libre" => "Averia Serif Libre", 
		"Bad Script" => "Bad Script",
		"Balthazar" => "Balthazar",
		"Bangers" => "Bangers",
		"Basic" => "Basic",
		"Baumans" => "Baumans",
		"Belgrano" => "Belgrano",
		"Belleza" => "Belleza",
		"Bentham" => "Bentham",
		"Berkshire Swash" => "Berkshire Swash",
		"Bevan" => "Bevan",
		"Bigshot One" => "Bigshot One",
		"Bilbo Swash Caps" => "Bilbo Swash Caps",
		"Bilbo" => "Bilbo",
		"Bitter" => "Bitter",
		"Black Ops One" => "Black Ops One ",
		"Bokor" => "Bokor",
		"Bonbon" => "Bonbon",
		"Boogaloo" => "Boogaloo",
		"Bowlby One SC" => "Bowlby One SC",
		"Bowlby One" => "Bowlby One",
		"Brawler" => "Brawler ",
		"Bree Serif" => "Bree Serif",
		"Bubblegum Sans" => "Bubblegum Sans",
		"Buda:light" => "Buda",
		"Buenard" => "Buenard",
		"Butcherman" => "Butcherman",
		"Butterfly Kids" => "Butterfly Kids",
		"Cabin Condensed" => "Cabin Condensed",
		"Cabin Sketch" => "Cabin Sketch",
		"Cabin Sketch:bold" => "Cabin Sketch Bold",
		"Cabin" => "Cabin",
		"Caesar Dressing" => "Caesar Dressing",
		"Cagliostro" => "Cagliostro",
		"Calligraffitti" => "Calligraffitti",
		"Cambo" => "Cambo",
		"Candal" => "Candal",
		"Cantarell" => "Cantarell",
		"Cantata One" => "Cantata One",
		"Capriola" => "Capriola",
		"Cardo" => "Cardo",
		"Carme" => "Carme ",
		"Carter One" => "Carter One",
		"Caudex" => "Caudex",
		"Cedarville Cursive" => "Cedarville Cursive",
		"Ceviche One" => "Ceviche One",
		"Changa One" => "Changa One",
		"Chango" => "Chango",
		"Chau Philomene One" => "Chau Philomene One",
		"Chelsea Market" => "Chelsea Market",
		"Cherry Cream Soda" => "Cherry Cream Soda",
		"Chewy" => "Chewy",
		"Chicle" => "Chicle",
		"Chivo" => "Chivo",
		"Coda" => "Coda",
		"Codystar" => "Codystar",
		"Comfortaa" => "Comfortaa ",
		"Coming Soon" => "Coming Soon",
		"Concert One" => "Concert One",
		"Condiment" => "Condiment",
		"Contrail One" => "Contrail One",
		"Convergence" => "Convergence",
		"Cookie" => "Cookie",
		"Copse" => "Copse",
		"Corben" => "Corben",
		"Corben:bold" => "Corben Bold",
		"Courgette" => "Courgette",
		"Cousine" => "Cousine",
		"Coustard" => "Coustard ",
		"Covered By Your Grace" => "Covered By Your Grace",
		"Crafty Girls" => "Crafty Girls",
		"Creepster" => "Creepster",
		"Crete Round" => "Crete Round",
		"Crimson Text" => "Crimson Text",
		"Crushed" => "Crushed",
		"Cuprum" => "Cuprum",
		"Cutive" => "Cutive",
		"Damion" => "Damion",
		"Dancing Script" => "Dancing Script",
		"Dawning of a New Day" => "Dawning of a New Day",
		"Days One" => "Days One ",
		"Delius Swash Caps" => "Delius Swash Caps ",
		"Delius Unicase" => "Delius Unicase ",
		"Delius" => "Delius ",
		"Della Respira" => "Della Respira",
		"Devonshire" => "Devonshire",
		"Didact Gothic" => "Didact Gothic",
		"Diplomata SC" => "Diplomata SC",
		"Diplomata" => "Diplomata",
		"Doppio One" => "Doppio One",
		"Dorsa" => "Dorsa",
		"Dosis" => "Dosis",
		"Dr Sugiyama" => "Dr Sugiyama",
		"Droid Sans Mono" => "Droid Sans Mono",
		"Droid Sans" => "Droid Sans",
		"Droid Serif" => "Droid Serif",
		"Duru Sans" => "Duru Sans",
		"Dynalight" => "Dynalight",
		"EB Garamond" => "EB Garamond",
		"Eagle Lake" => "Eagle Lake",
		"Eater" => "Eater",
		"Economica" => "Economica",
		"Electrolize" => "Electrolize",
		"Emblema One" => "Emblema One",
		"Emilys Candy" => "Emilys Candy",
		"Engagement" => "Engagement",
		"Enriqueta" => "Enriqueta",
		"Erica One" => "Erica One",
		"Esteban" => "Esteban",
		"Euphoria Script" => "Euphoria Script",
		"Ewert" => "Ewert",
		"Exo" => "Exo",
		"Expletus Sans" => "Expletus Sans",
		"Fanwood Text" => "Fanwood Text",
		"Fascinate Inline" => "Fascinate Inline",
		"Fascinate" => "Fascinate",
		"Fasthand" => "Fasthand",
		"Federant" => "Federant",
		"Federo" => "Federo ",
		"Felipa" => "Felipa",
		"Fjord One" => "Fjord One",
		"Flamenco" => "Flamenco",
		"Flavors" => "Flavors",
		"Fondamento" => "Fondamento",
		"Fontdiner Swanky" => "Fontdiner Swanky",
		"Forum" => "Forum",
		"Francois One" => "Francois One",
		"Fredoka One" => "Fredoka One",
		"Fresca" => "Fresca",
		"Frijole" => "Frijole",
		"Fugaz One" => "Fugaz One",
		"Galdeano" => "Galdeano",
		"Galindo" => "Galindo",
		"Gentium Basic" => "Gentium Basic",
		"Gentium Book Basic" => "Gentium Book Basic ",
		"Geo" => "Geo",
		"Geostar Fill" => "Geostar Fill",
		"Geostar" => "Geostar ",
		"Germania One" => "Germania One",
		"Give You Glory" => "Give You Glory",
		"Glass Antiqua" => "Glass Antiqua",
		"Glegoo" => "Glegoo",
		"Gloria Hallelujah" => "Gloria Hallelujah ",
		"Goblin One" => "Goblin One",
		"Gochi Hand" => "Gochi Hand",
		"Gorditas" => "Gorditas",
		"Graduate" => "Graduate",
		"Gravitas One" => "Gravitas One",
		"Great Vibes" => "Great Vibes",
		"Gruppo" => "Gruppo",
		"Gudea" => "Gudea",
		"Habibi" => "Habibi",
		"Hammersmith One" => "Hammersmith One",
		"Handlee" => "Handlee",
		"Happy Monkey" => "Happy Monkey",
		"Henny Penny" => "Henny Penny",
		"Herr Von Muellerhoff" => "Herr Von Muellerhoff",
		"Holtwood One SC" => "Holtwood One SC",
		"Homemade Apple" => "Homemade Apple",
		"Homenaje" => "Homenaje",
		"IM Fell DW Pica SC" => "IM Fell DW Pica SC",
		"IM Fell DW Pica" => "IM Fell DW Pica",
		"IM Fell DW Pica:regular,italic" => "IM Fell DW Pica (plus italic)",
		"IM Fell Double Pica SC" => "IM Fell Double Pica SC",
		"IM Fell Double Pica" => "IM Fell Double Pica",
		"IM Fell English SC" => "IM Fell English SC",
		"IM Fell English" => "IM Fell English",
		"IM Fell French Canon SC" => "IM Fell French Canon SC",
		"IM Fell French Canon" => "IM Fell French Canon",
		"IM Fell Great Primer SC" => "IM Fell Great Primer SC",
		"IM Fell Great Primer" => "IM Fell Great Primer",
		"Iceberg" => "Iceberg",
		"Iceland" => "Iceland",
		"Imprima" => "Imprima",
		"Inconsolata" => "Inconsolata",
		"Inder" => "Inder",
		"Indie Flower" => "Indie Flower",
		"Inika" => "Inika",
		"Irish Grover" => "Irish Grover",
		"Irish Growler" => "Irish Growler",
		"Istok Web" => "Istok Web",
		"Italiana" => "Italiana",
		"Italianno" => "Italianno",
		"Jim Nightshade" => "Jim Nightshade",
		"Jockey One" => "Jockey One",
		"Jolly Lodger" => "Jolly Lodger",
		"Josefin Sans" => "Josefin Sans",
		"Josefin Slab" => "Josefin Slab",
		"Judson" => "Judson",
		"Julee" => "Julee",
		"Junge" => "Junge",
		"Jura" => " Jura",
		"Just Another Hand" => "Just Another Hand",
		"Just Me Again Down Here" => "Just Me Again Down Here",
		"Kameron" => "Kameron",
		"Karla" => "Karla",
		"Kaushan Script" => "Kaushan Script",
		"Kelly Slab" => "Kelly Slab ",
		"Kenia" => "Kenia",
		"Knewave" => "Knewave",
		"Kotta One" => "Kotta One",
		"Kranky" => "Kranky",
		"Kreon" => "Kreon",
		"Kristi" => "Kristi",
		"Krona One" => "Krona One",
		"La Belle Aurore" => "La Belle Aurore",
		"Lancelot" => "Lancelot",
		"League Script" => "League Script",
		"Leckerli One" => "Leckerli One ",
		"Ledger" => "Ledger",
		"Lekton" => " Lekton ",
		"Lemon" => "Lemon",
		"Life Savers" => "Life Savers",
		"Lilita One" => "Lilita One",
		"Limelight" => " Limelight ",
		"Linden Hill" => "Linden Hill",
		"Lobster Two" => "Lobster Two",
		"Lobster" => "Lobster",
		"Londrina Outline" => "Londrina Outline",
		"Londrina Shadow" => "Londrina Shadow",
		"Londrina Sketch" => "Londrina Sketch",
		"Londrina Solid" => "Londrina Solid",
		"Lora" => "Lora",
		"Love Ya Like A Sister" => "Love Ya Like A Sister",
		"Lovers Quarrel" => "Lovers Quarrel",
		"Loved by the King" => "Loved by the King",
		"Luckiest Guy" => "Luckiest Guy",
		"Lusitana" => "Lusitana",
		"Lustria" => "Lustria",
		"Macondo Swash Caps" => "Macondo Swash Caps",
		"Macondo" => "Macondo",
		"Magra" => "Magra",
		"Maiden Orange" => "Maiden Orange",
		"Mako" => "Mako",
		"Marck Script" => "Marck Script",
		"Marko One" => "Marko One",
		"Marmelad" => "Marmelad",
		"Marvel" => "Marvel ",
		"Mate SC" => "Mate SC",
		"Mate" => "Mate",
		"Maven Pro" => " Maven Pro",
		"McLaren" => "McLaren",
		"Meddon" => "Meddon",
		"MedievalSharp" => "MedievalSharp",
		"Medula One" => "Medula One",
		"Megrim" => "Megrim",
		"Merienda One" => "Merienda One",
		"Merriweather" => "Merriweather",
		"Metamorphous" => "Metamorphous",
		"Metrophobic" => "Metrophobic",
		"Metal Mania" => "Metal Mania",
		"Michroma" => "Michroma",
		"Miltonian Tattoo" => "Miltonian Tattoo",
		"Miltonian" => "Miltonian",
		"Miniver" => "Miniver",
		"Miss Fajardose" => "Miss Fajardose",
		"Miss Saint Delafield" => "Miss Saint Delafield",
		"Modern Antiqua" => "Modern Antiqua",
		"Molengo" => "Molengo",
		"Monofett" => "Monofett",
		"Monoton" => "Monoton ",
		"Monsieur La Doulaise" => "Monsieur La Doulaise",
		"Montaga" => "Montaga",
		"Montez" => "Montez ",
		"Montserrat" => "Montserrat",
		"Mountains of Christmas" => "Mountains of Christmas",
		"Mr Bedford" => "Mr Bedford",
		"Mr Dafoe" => "Mr Dafoe",
		"Mr De Haviland" => "Mr De Haviland",
		"Mrs Saint Delafield" => "Mrs Saint Delafield",
		"Mrs Sheppards" => "Mrs Sheppards",
		"Muli" => "Muli",
		"Mystery Quest" => "Mystery Quest",
		"Neucha" => "Neucha",
		"Neuton" => "Neuton",
		"News Cycle" => "News Cycle",
		"Niconne" => "Niconne",
		"Nixie One" => "Nixie One",
		"Nobile" => "Nobile",
		"Nokora" => "Nokora",
		"Norican" => "Norican",
		"Nosifer" => "Nosifer",
		"Noticia Text" => "Noticia Text",
		"Nova Cut" => "Nova Cut",
		"Nova Flat" => "Nova Flat",
		"Nova Mono" => "Nova Mono",
		"Nova Oval" => "Nova Oval",
		"Nova Round" => "Nova Round",
		"Nova Script" => "Nova Script",
		"Nova Slim" => "Nova Slim",
		"Nova Square" => "Nova Square",
		"Numans" => "Numans ",
		"Nunito" => " Nunito Regular",
		"Nunito:light" => " Nunito Light",
		"OFL Sorts Mill Goudy TT" => "OFL Sorts Mill Goudy TT",
		"Old Standard TT" => "Old Standard TT",
		"Oldenburg" => "Oldenburg",
		"Oleo Script" => "Oleo Script",
		"Open Sans" => "Open Sans",
		"Orbitron" => "Orbitron",
		"Oregano" => "Oregano",
		"Original Surfer" => "Original Surfer",
		"Oswald" => "Oswald",
		"Over the Rainbow" => "Over the Rainbow",
		"Overlock SC" => "Overlock SC",
		"Overlock" => "Overlock",
		"Ovo" => "Ovo ",
		"Oxygen" => "Oxygen",
		"PT Mono" => "PT Mono",
		"PT Sans Caption" => "PT Sans Caption",
		"PT Sans Narrow" => "PT Sans Narrow",
		"PT Sans" => "PT Sans",
		"PT Serif Caption" => "PT Serif Caption",
		"PT Serif" => "PT Serif",
		"Pacifico" => "Pacifico",
		"Parisienne" => "Parisienne",
		"Passero One" => "Passero One",
		"Passion One" => "Passion One",
		"Patrick Hand" => "Patrick Hand",
		"Patua One" => "Patua One",
		"Paytone One" => "Paytone One",
		"Peralta" => "Peralta",
		"Permanent Marker" => "Permanent Marker",
		"Petrona" => "Petrona",
		"Philosopher" => "Philosopher",
		"Piedra" => "Piedra",
		"Pinyon Script" => "Pinyon Script",
		"Plaster" => "Plaster",
		"Play" => "Play",
		"Playball" => "Playball",
		"Playfair Display" => " Playfair Display ",
		"Podkova" => " Podkova ",
		"Poiret One" => "Poiret One",
		"Poller One" => "Poller One",
		"Poly" => "Poly",
		"Pompiere" => "Pompiere ",
		"Pontano Sans" => "Pontano Sans",
		"Port Lligat Sans" => "Port Lligat Sans",
		"Port Lligat Slab" => "Port Lligat Slab",
		"Prata" => "Prata",
		"Press Start 2P" => "Press Start 2P",
		"Princess Sofia" => "Princess Sofia",
		"Prociono" => "Prociono",
		"Prosto One" => "Prosto One",
		"Puritan" => "Puritan",
		"Quando" => "Quando",
		"Quantico" => "Quantico",
		"Quattrocento Sans" => "Quattrocento Sans",
		"Quattrocento" => "Quattrocento",
		"Questrial" => "Questrial ",
		"Quicksand" => "Quicksand",
		"Qwigley" => "Qwigley",
		"Racing Sans One" => "Racing Sans One",
		"Radley" => "Radley",
		"Rammetto One" => "Rammetto One",
		"Rancho" => "Rancho",
		"Rationale" => "Rationale ",
		"Redressed" => "Redressed",
		"Reenie Beanie" => "Reenie Beanie",
		"Revalia" => "Revalia",
		"Ribeye Marrow" => "Ribeye Marrow",
		"Ribeye" => "Ribeye",
		"Righteous" => "Righteous",
		"Rochester" => "Rochester ",
		"Rock Salt" => "Rock Salt",
		"Rokkitt" => "Rokkitt",
		"Romanesco" => "Romanesco",
		"Ropa Sans" => "Ropa Sans",
		"Rosario" => "Rosario ",
		"Rouge Script" => "Rouge Script",
		"Ruda" => "Ruda",
		"Ruge Boogie" => "Ruge Boogie",
		"Ruluko" => "Ruluko",
		"Ruslan Display" => "Ruslan Display",
		"Russo One" => "Russo One",
		"Ruthie" => "Ruthie",
		"Sail" => "Sail",
		"Salsa" => "Salsa",
		"Sancreek" => "Sancreek",
		"Sansita One" => "Sansita One",
		"Sarina" => "Sarina",
		"Satisfy" => "Satisfy",
		"Schoolbell" => "Schoolbell",
		"Seaweed Script" => "Seaweed Script",
		"Sevillana" => "Sevillana",
		"Shadows Into Light Two" => "Shadows Into Light Two",
		"Shadows Into Light" => "Shadows Into Light",
		"Shanti" => "Shanti",
		"Share" => "Share",
		"Shojumaru" => "Shojumaru",
		"Short Stack" => "Short Stack ",
		"Sigmar One" => "Sigmar One",
		"Signika Negative" => "Signika Negative",
		"Signika" => "Signika",
		"Simonetta" => "Simonetta",
		"Sirin Stencil" => "Sirin Stencil",
		"Six Caps" => "Six Caps",
		"Slackey" => "Slackey",
		"Smokum" => "Smokum ",
		"Smythe" => "Smythe",
		"Snippet" => "Snippet ",
		"Sofia" => "Sofia",
		"Sonsie One" => "Sonsie One",
		"Sorts Mill Goudy" => "Sorts Mill Goudy",
		"Source Sans Pro" => "Source Sans Pro",
		"Special Elite" => "Special Elite",
		"Spicy Rice" => "Spicy Rice",
		"Spinnaker" => "Spinnaker",
		"Spirax" => "Spirax",
		"Squada One" => "Squada One",
		"Stardos Stencil" => "Stardos Stencil",
		"Stint Ultra Condensed" => "Stint Ultra Condensed",
		"Stint Ultra Expanded" => "Stint Ultra Expanded",
		"Stoke" => "Stoke",
		"Sue Ellen Francisco" => "Sue Ellen Francisco",
		"Sunshiney" => "Sunshiney",
		"Supermercado One" => "Supermercado One",
		"Swanky and Moo Moo" => "Swanky and Moo Moo",
		"Syncopate" => "Syncopate",
		"Tangerine" => "Tangerine",
		"Telex" => "Telex",
		"Tenor Sans" => " Tenor Sans ",
		"Terminal Dosis" => "Terminal Dosis",
		"Terminal Dosis Light" => "Terminal Dosis Light",
		"The Girl Next Door" => "The Girl Next Door",
		"Tinos" => "Tinos",
		"Titan One" => "Titan One",
		"Trade Winds" => "Trade Winds",
		"Trocchi" => "Trocchi",
		"Trochut" => "Trochut",
		"Trykker" => "Trykker",
		"Tulpen One" => "Tulpen One ",
		"Ubuntu Condensed" => "Ubuntu Condensed",
		"Ubuntu Mono" => "Ubuntu Mono",
		"Ubuntu" => "Ubuntu",
		"Ultra" => "Ultra",
		"Uncial Antiqua" => "Uncial Antiqua",
		"UnifrakturCook:bold" => "UnifrakturCook",
		"UnifrakturMaguntia" => "UnifrakturMaguntia",
		"Unkempt" => "Unkempt",
		"Unlock" => "Unlock",
		"Unna" => "Unna ",
		"VT323" => "VT323",
		"Varela Round" => "Varela Round",
		"Varela" => "Varela",
		"Vast Shadow" => "Vast Shadow",
		"Vibur" => "Vibur",
		"Vidaloka" => "Vidaloka ",
		"Viga" => "Viga",
		"Voces" => "Voces",
		"Volkhov" => "Volkhov ",
		"Vollkorn" => "Vollkorn",
		"Voltaire" => "Voltaire ",
		"Waiting for the Sunrise" => "Waiting for the Sunrise",
		"Wallpoet" => "Wallpoet",
		"Walter Turncoat" => "Walter Turncoat",
		"Wellfleet" => "Wellfleet",
		"Wire One" => "Wire One",
		"Yanone Kaffeesatz" => "Yanone Kaffeesatz",
		"Yellowtail" => "Yellowtail ",
		"Yeseva One" => "Yeseva One",
		"Yesteryear" => "Yesteryear",
		"Zeyada" => "Zeyada"
		);		


//Folder Paths for "type" => "images"
$panelurl =  get_template_directory_uri() . '/admin/images/panel-layouts/';


/*-----------------------------------------------------------------------------------*/
/* Create The Custom Site Options Panel
/*-----------------------------------------------------------------------------------*/
$options = array(); // do not delete this line - sky will fall

/* Option Page 1 - All Options */	


	
$options[] = array( "name" => __('Colors & Font','framework_localize'),
			"type" => "heading");
			
			

			
			$options[] = array( "name" => __('Highlight Color','framework_localize'),
			"desc" => __('Links and buttons color.','framework_localize'),
			"id" => $shortname."_highlight_color",
			"std" => "#FF675B",
			"type" => "color");	
			
			$options[] = array( "name" => __('Header Background Image','framework_localize'),
			"desc" => __('','framework_localize'),
			"id" => $shortname."_header_bg",
			"std" => "",
			"type" => "upload");
			
			$options[] = array( "name" => __('Button Font Color','framework_localize'),
			"desc" => __('Default button font color.','framework_localize'),
			"id" => $shortname."_font_color",
			"std" => "",
			"type" => "color");	
			
			$options[] = array( "name" => __('Font','framework_localize'),
			"desc" => __('Select a font.','framework_localize'),
			"id" => $shortname."_font_selection",
			"std" => "Bokor",
			"type" => "select",
			"options" => $font_array);
			
			$options[] = array( "name" => __('Header & Menu Font Color','framework_localize'),
			"desc" => __('Default button font color.','framework_localize'),
			"id" => $shortname."_header_font_color",
			"std" => "",
			"type" => "color");	
			
			$options[] = array( "name" => __('Logo & Favicon','framework_localize'),
			"type" => "heading");
			
			$options[] = array( "name" => __('Website Logo','framework_localize'),
			"desc" => __('Upload a custom logo for your Website.','framework_localize'),
			"id" => $shortname."_sitelogo",
			"std" => "",
			"type" => "upload");
			
			$options[] = array( "name" => __('Favicon','framework_localize'),
			"desc" => __('Upload a 32px x 32px image that will represent your website\'s favicon.','framework_localize'),
			"id" => $shortname."_favicon",
			"std" => "",
			"type" => "upload");
			
	
			
			$options[] = array( "name" => __('Home Page','framework_localize'),
			"type" => "heading");
			
			$options[] = array( "name" => __('Banner Heading','framework_localize'),
			"id" => $shortname."_banner",
			"std" => "",
			"type" => "text");
			
			$options[] = array( "name" => __('Banner Sub-heading','framework_localize'),
			"id" => $shortname."_banner_sub",
			"std" => "",
			"type" => "text");
			
			
			$options[] = array( "name" => __('Slider Slug','framework_localize'),
			"id" => $shortname."_slider_slug",
			"std" => "slider1",
			"type" => "text");
			
			
			
			$options[] = array( "name" => __('Footer','framework_localize'),
			"type" => "heading");
			
			$options[] = array( "name" => __('Copyright Text','framework_localize'),
			"id" => $shortname."_copyright_text",
			"std" => "© reverb 2012",
			"type" => "text");
			
			$options[] = array( "name" => __('Sidebar','framework_localize'),
			"type" => "heading");
			
			$options[] = array( "name" => __('Sidebar','framework_localize'),
			"desc" => __('set sidebars globally to appear on the right or left.','framework_localize'),
			"id" => $shortname."_sidebar_location",
			"std" => "option1",
			"type" => "images",
			"options" => array(
				'option2' => $panelurl . 'layout-1.png',
				'option1' => $panelurl . 'layout-2.png',
				));
			
			
			$options[] = array( "name" => __('Social Media','framework_localize'),
			"type" => "heading");
			
			$options[] = array( "name" => __('Twitter Name','framework_localize'),
			"desc" => __('enter twitter username','framework_localize'),
			"id" => $shortname."_social_twitname",
			"std" => "",
			"type" => "text");
			
			$options[] = array( "name" => __('Number of Tweets to Display','framework_localize'),
			"desc" => __('enter a number','framework_localize'),
			"id" => $shortname."_social_tweets",
			"std" => "",
			"type" => "text");
			
				$options[] = array( "name" => __('Facebook Username','framework_localize'),
			"desc" => __('enter facebook username','framework_localize'),
			"id" => $shortname."_social_facebook",
			"std" => "",
			"type" => "text");
			
				$options[] = array( "name" => __('Pinterest URL','framework_localize'),
			"desc" => __('enter pinterest url','framework_localize'),
			"id" => $shortname."_social_pinterest",
			"std" => "",
			"type" => "text");
			
				$options[] = array( "name" => __('LinkedIn URL','framework_localize'),
			"desc" => __('enter linkedin url','framework_localize'),
			"id" => $shortname."_social_linkedin",
			"std" => "",
			"type" => "text");
			
				$options[] = array( "name" => __('Google +1 URL','framework_localize'),
			"desc" => __('enter google +1 url','framework_localize'),
			"id" => $shortname."_social_googleplus",
			"std" => "",
			"type" => "text");
			
				$options[] = array( "name" => __('Github URL','framework_localize'),
			"desc" => __('enter github url','framework_localize'),
			"id" => $shortname."_social_github",
			"std" => "",
			"type" => "text");
			
				$options[] = array( "name" => __('RSS','framework_localize'),
			"desc" => __('enter rss feed','framework_localize'),
			"id" => $shortname."_social_rss",
			"std" => "",
			"type" => "text");
			
			$options[] = array( "name" => __('YouTube','framework_localize'),
			"desc" => __('enter youtube url','framework_localize'),
			"id" => $shortname."_social_youtube",
			"std" => "",
			"type" => "text");
			
			$options[] = array( "name" => __('Instagram','framework_localize'),
			"desc" => __('enter instagram url','framework_localize'),
			"id" => $shortname."_social_instagram",
			"std" => "",
			"type" => "text");
			
			$options[] = array( "name" => __('Email','framework_localize'),
			"desc" => __('enter email','framework_localize'),
			"id" => $shortname."_social_email",
			"std" => "",
			"type" => "text");
			
			
			$options[] = array( "name" => __('Google Map','framework_localize'),
			"type" => "heading");
			
			$options[] = array( "name" => __('Display Google Map','framework_localize'),
			"desc" => __('Show map on contact page.','framework_localize'),
			"id" => $shortname."_gmap_check",
			"std" => "true",
			"type" => "checkbox");
			
			$options[] = array( "name" => __('Map Latitude','framework_localize'),
			"desc" => __('paste in latitude','framework_localize'),
			"id" => $shortname."_gmap_lat",
			"std" => "",
			"type" => "text");
			
			$options[] = array( "name" => __('Map Longitude','framework_localize'),
			"desc" => __('paste in longitude','framework_localize'),
			"id" => $shortname."_gmap_long",
			"std" => "",
			"type" => "text");
			
			$options[] = array( "name" => __('Map Zoom Level','framework_localize'),
			"desc" => __('enter zoom level','framework_localize'),
			"id" => $shortname."_gmap_zoom",
			"std" => "12",
			"type" => "text");
	
			
			$options[] = array( "name" => __('Analytics','framework_localize'),
			"type" => "heading");
			
									   
$options[] = array( "name" => __('Tracking Code','framework_localize'),
			"desc" => __('Paste Google Analytics (or other) tracking code here.','framework_localize'),
			"id" => $shortname."_google_analytics",
			"std" => "",
			"type" => "textarea");
	



update_option('of_template',$options); 					  
  
update_option('of_shortname',$shortname);

}
}
?>